---
server:
  image: "iidlx/hanlonjson"
  ports: 
    - 8026:8026
    - 69:69/udp
  privileged: true
  env_file: hanlon.env
#  environment:
#    DOCKER_HOST: "${DOCKER_HOST}"
#    HANLON_SUBNETS: "${HANLON_SUBNETS}"